sudo: false
language: rust
matrix:
  include:
    - rust: nightly
      # env:
      #   # will have to be commented out the following line
      #   - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    - rust: beta
    - rust: 1.13.0

script:
  - cp src/settings.toml.sample src/settings.toml
  - cargo build
